all:
  children:
    app_servers:
      hosts:
        app-server:
          ansible_host: 34.186.24.52
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    gitlab:
      hosts:
        gitlab-server:
          ansible_host: 34.50.169.169
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
