---
- name: Deploy Docker-based service
  hosts: all
  become: true
  vars:
    service_name: "{{ service_name | default('skillbox-app') }}"
    image_name: "{{ docker_image | default('maxpack2030/skillbox-app') }}"
    image_tag: "{{ image_tag | default('latest') }}"
  
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Deploy systemd unit file for service
      template:
        src: ../templates/service.service.j2
        dest: /etc/systemd/system/{{ service_name }}.service
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and restart service
      systemd:
        name: "{{ service_name }}"
        enabled: yes
        state: restarted
